### ISSUE TITLE
Crashes on Couldron 1.7.10 Server

### ISSUE THREAD

**Issue by larsvu** [LatvianModder/LatCoreMC#11]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 5-3-15 15:27
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:317)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313632096 bytes (299 MB) / 436731904 bytes (416 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xmx3G -Xms128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 34 mods loaded, 34 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.25.1207} [Forge Mod Loader] (bukkit.jar) Unloaded
	Forge{10.13.0.1207} [Minecraft Forge] (bukkit.jar) Unloaded
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded
	securitycraft{v1.7.3} [SecurityCraft] ([1.7.10] SecurityCraft 1.7.3.jar) Unloaded
	AdvancedMachines{1.0.9} [IC2 Advanced Machines Addon] (Advanced-Machines-Addon-1.7.10.jar) Unloaded
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (Advanced-Solar-Panels-Addon-1.7.10.jar) Unloaded
	asielib{0.2.7} [asielib] (AsieLib-1.7.10.zip) Unloaded
	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) Unloaded
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded
	EE3{0.2.434} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.2.434.jar) Unloaded
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded
	gvc{0.4.0} [Gliby's Voice Chat Mod] (GlibysVC-1710_040.jar) Unloaded
	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded
	LatBlocks{1.6.7} [LatBlocks] (LatBlocks-1.7.10-1.6.7.jar) Unloaded
	LatCoreMC{1.6.7} [LatCoreMC] (LatCoreMC-1.7.10-1.6.7.jar) Unloaded
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded
	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) Unloaded
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded
	statues{2.1.3} [Statues] (Statues-Mod-1.7.10.zip) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by LatvianModder** [comment]
Hmm, this is wierd, try removing both LatCoreMC and LatBlocks, and if it still crashes, then its not my problem :P I can't really tell, because these MissingModsExceptions are so non-informative xP

**Comment by larsvu** [comment]
If i remove them they work fine

**Comment by LatvianModder** [comment]
Is it still crashing?

**Comment by larsvu** [comment]
Yes it is

**Comment by LatvianModder** [comment]
.. But how you can have it, if its discontinued?
http://cauldron.minecraftforge.net/

Im almost 100% sure that it's an old Forge version (forge is listed as required mod in LatCoreMC), all LatMods require Forge 10.13.2.1291+

**Comment by larsvu** [comment]
I see, it's an older version yeah. it's 10.13.0.1207, I will check if i can update it

**Comment by larsvu** [comment]
What happends if you remove it from the required mods?

**Comment by LatvianModder** [comment]
I'd have to downgrade my dev-env, check for errors, build it, then upload it in dropbox, link to you and updgrade my dev-env again. The end. But I can try :D

**Comment by larsvu** [comment]
I will love you :P

**Comment by larsvu** [comment]
But that does mean that emc condencer also needs the higher version doesn't it?

**Comment by LatvianModder** [comment]
EMCC only depends on LatCoreMC, and only LatCoreMC has the forge dependency.
Can we move to IRC? (irc.esper.net #LatMod) Because I don't want this to turn into a chat xP Closing this issue, since the issue was older Forge version.

**Comment by LatvianModder** [comment]
For anyone else wanting to play with Cal:
