### ISSUE TITLE
Crash with Fastcraft

### ISSUE THREAD

**Issue by crunkazcanbe** [LatvianModder/LatCoreMC#6]
As the title says your mod crashes as soon as i add it to my pack with fastcraft . I have to have fastcraft or 1.7.10 does not play that smooth BTW I don't know why its saying heap space in the crash I have java 8 with 4 gigs given to MC crash is here http://pastebin.com/92KVJGd0 . Is there a memory leak in your mod ? Just wondering because with the few mods I have installed and 4 gigs given to mc it is more then enough ram , because I never see mc use over 2 gigs with the amount of mods I have .

**Comment by LatvianModder** [comment]
Hmm that is related to one of my texture experiments, I will fix this asap.

**Comment by crunkazcanbe** [comment]
Thanx man . I love your mod , and it works nice by its self just like I said its only when I toss it in with other mods. :)

**Comment by LatvianModder** [comment]
Fixed in https://github.com/LatvianModder/LatCoreMC/commit/5450a66b8f1ac6c751bce5a2ab653150d68e9b8a
Version 1.6.6.2 will be out shortly
